### ISSUE TITLE
Unexpected error fetching Omnilogic data: syntax error: line 1, column 0

### ISSUE THREAD

**Issue by edrikk** [djtimca/haomnilogic#7]
Hi there,
As at Release 6 (June 4th), I am seeing the following error in the Home Assistant logs,
Info is still loaded correctly however as far as I can tell.

I am running Home Assistant in an Unraid Docker.

> [31m2022-06-04 16:33:08 ERROR (MainThread) [custom_components.omnilogic.common] Unexpected error fetching Omnilogic data: syntax error: line 1, column 0
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/omnilogic/common.py", line 47, in _async_update_data
data = await self.api.get_telemetry_data()
File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 1008, in get_telemetry_data
site_telem = self.telemetry_to_json(telem, config_item, self.alarms_to_json(this_alarm))
File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 719, in telemetry_to_json
telemetryXML = ElementTree.fromstring(telemetry)
File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1349, in XML
parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0[0m
[31m2022-06-04 16:33:25 ERROR (MainThread) [custom_components.omnilogic.common] Unexpected error fetching Omnilogic data: syntax error: line 1, column 0
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/omnilogic/common.py", line 47, in _async_update_data
data = await self.api.get_telemetry_data()
File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 974, in get_telemetry_data
config_data = await self.get_msp_config_file()
File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 228, in get_msp_config_file
configitem = self.convert_to_json(mspconfig)
File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 1048, in convert_to_json
my_dict = xmltodict.parse(xmlString)
File "/usr/local/lib/python3.9/site-packages/xmltodict.py", line 327, in parse
parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0[0m

**Comment by djtimca** [comment]
Thanks - this appears to be coming from the API component that interfaces with Hayward. I will be looking at this and a couple other issues there this week.

**Comment by sddgit** [comment]
Something similar here:

```
This error originated from a custom integration.

Logger: custom_components.omnilogic.common
Source: custom_components/omnilogic/common.py:47 
Integration: Omnilogic 
First occurred: June 5, 2022, 11:07:22 PM (3 occurrences) 
Last logged: 3:11:50 AM

Unexpected error fetching Omnilogic data: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/omnilogic/common.py", line 47, in _async_update_data
    data = await self.api.get_telemetry_data()
  File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 1008, in get_telemetry_data
    site_telem = self.telemetry_to_json(telem, config_item, self.alarms_to_json(this_alarm))
  File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 719, in telemetry_to_json
    telemetryXML = ElementTree.fromstring(telemetry)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```
When this happens, all entities go unavailable, then recover after 6 seconds (presumably, the next poll).

**Comment by djtimca** [comment]
Should be fixed in latest release.

**Comment by edrikk** [comment]
Confirmed.  No longer seeing the error.  Great job!

**Comment by sddgit** [comment]
Not seeing the original error, but I’ve now got 2 of these - again all equipment goes unavailable.

```
This error originated from a custom integration.

Logger: custom_components.omnilogic.common
Source: helpers/update_coordinator.py:223 
Integration: Omnilogic 
First occurred: 10:07:40 AM (2 occurrences) 
Last logged: 11:40:54 AM

Error fetching Omnilogic data: Error updating from OmniLogic: Error converting Hayward data to JSON.
```

**Comment by djtimca** [comment]
@sddgit yes the error is now handled more gracefully. I'm going to play with things in the integration to see if I can't make that a bit nicer too.

**Comment by sddgit** [comment]
Sorry, not with you. What causes this particular “error converting Hayward data to JSON”? I’m still seeing it, but have not updated to your later version yet. Will that version overcome the issue somehow?

Thanks for all your efforts.

**Comment by djtimca** [comment]
@sddgit the issue occurs when the data returned from Hayward is invalid. The error just signifies that the current update failed. It is standard for cloud integrations to have occasional hiccups in the data.

**Comment by sddgit** [comment]
Ok, thanks for that. I guess it could be an issue if a schedule tried to turn something on/off at the time the equipment goes unavailable. But oh well!

**Comment by djtimca** [comment]
It isn't supposed to. The integration uses the standard HA UpdateFailed error which should just wait for the next update. 

Any service calls for on/off etc are called regardless of whether the last status poll was successful or not.

**Comment by sddgit** [comment]
At the exact time of the error, Logbook shows every sensor/switch becomes unavailable. Then a few seconds later (15 seconds the last time it happened), they all show off or on depending on their state. I would think any action taken during this window would get an error of some sort?

**Comment by djtimca** [comment]
Shouldn't get any errors, at least I haven't seen one in 3 years of using it (with the original errors).

**Comment by sddgit** [comment]
Got one of these (which used to happen a lot, but I thought you’d fixed it):
```
This error originated from a custom integration.

Logger: custom_components.omnilogic.common
Source: custom_components/omnilogic/common.py:47 
Integration: Omnilogic 
First occurred: June 8, 2022, 11:01:00 PM (1 occurrences) 
Last logged: June 8, 2022, 11:01:00 PM

Unexpected error fetching Omnilogic data: syntax error: line 1, column 0
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/omnilogic/common.py", line 47, in _async_update_data
    data = await self.api.get_telemetry_data()
  File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 1006, in get_telemetry_data
    site_alarms = self.alarms_to_json(this_alarm)
  File "/usr/local/lib/python3.9/site-packages/omnilogic/__init__.py", line 694, in alarms_to_json
    alarmsXML = ElementTree.fromstring(alarms)
  File "/usr/local/lib/python3.9/xml/etree/ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```
And still these (5 in the last 20 hours):
```
This error originated from a custom integration.

Logger: custom_components.omnilogic.common
Source: helpers/update_coordinator.py:223 
Integration: Omnilogic 
First occurred: June 8, 2022, 12:42:28 PM (5 occurrences) 
Last logged: 4:21:16 AM

Error fetching Omnilogic data: Error updating from OmniLogic: Error converting Hayward data to JSON.
Error fetching Omnilogic data: Error updating from OmniLogic: Error loading Hayward data.
```
Am I right in thinking that 1.0.8 is designed to alleviate the “unavailable” problems these cause? I think it would be good to find out the underlying cause of why I’m seeing a relatively large number of the errors.

**Comment by djtimca** [comment]
1.0.8 I'm hoping will fix the second one. Will have to look separately at the first one. Can you please open a separate issue with the first error message since it is different than the others that I solved earlier. 

Thanks

**Comment by sddgit** [comment]
OK. Will do. I just installed 1.0.8. A short while after the HA restart, I saw all the equipment go unavailable for a short while, and this was in the log:
```
This error originated from a custom integration.

Logger: custom_components.omnilogic.common
Source: helpers/update_coordinator.py:197 
Integration: Hayward Omnilogic 
First occurred: 9:04:06 AM (1 occurrences) 
Last logged: 9:04:06 AM

Timeout fetching Omnilogic data
```

**Comment by djtimca** [comment]
Ugh. Ok will do more looking at solutions. It appears that this is how Home Assistant wants cloud integrations to work when you have a timeout. Much more graceful than before but still not ideal.

**Comment by sddgit** [comment]
Yeh, a ideally a timeout shouldn’t result in anything going unavailable. It would make automations a little unreliable. 

Thanks for all the work you’re putting into this.

**Comment by djtimca** [comment]
A timeout should not affect automations. Even if there is a timeout the service calls for on/off etc should be called as well. 

Just affects the UI and logs really.

**Comment by djtimca** [comment]
My understanding is that it shouldn't and I have never seen an issue with my own.

**Comment by sddgit** [comment]
I’m thinking of an automation that, for example, checks the status of a pump, or an air temperature before doing something else. I would have thought that check would fail somehow if that switch/sensor was unavailable. But I’m pretty new to HA, so I’m just guessing! Anyway, if you think of some way to improve things, it would always be welcome.
